### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined while exporting to Excel

### ISSUE THREAD

**Issue by prnvlohkre** [AlaSQL/alasql#1109]
While exporting the excel file i get the error saying "Uncaught TypeError: Cannot read property 'length' of undefined".
The scenario is : i have 6 different table which contains different data.When i am going to export it to excel sheet, it should create different 6 sheets in the Excel workbook.
When i have 1 empty table having no data, it creates an excel workbook with 1 empty sheet/tab but when i have more than 1 empty table, it fails to create an excel sheet and throws an error.

here is my query for the same.

var opts = [{sheetid:"Operations",header:true},{sheetid:"Operation Hooks",header:true},{sheetid:"Tool Groups",header:true},{sheetid:"BuyOffs",header:true},{sheetid:"Data Collection Groups",header:true},{sheetid:"DC Params",header:true}];
  		alasql('SELECT INTO XLSX(" ' + saveFile + '.xlsx", ?) FROM ?', [opts,[data,data1,data2,data3,data4,data5]]);

where data,data1,data2,data3,data4,data5 are the the data model(array) having the table data.

can someone please look into this. it needs to resolve in an urgency.

**Comment by prnvlohkre** [comment]
can anyone help me out in this

**Comment by maelon** [comment]
maybe opts is empty，it happened to me the same

**Comment by mathiasrw** [comment]
Any chance you can create an example on jsfiddle that generates this error?

**Comment by artikhot97** [comment]
Getting Same error :face_with_rolling_eyes:

**Comment by mathiasrw** [comment]
@artikhot97 Any chance you can create an example on jsfiddle that generates this error?

**Comment by gkkachi** [comment]
Hi @prnvlohkre @mathiasrw 

Apply the patch file below and it works fine for me.

```alasql+4.2.5.patch
diff --git a/node_modules/alasql/dist/alasql.fs.js b/node_modules/alasql/dist/alasql.fs.js
index 0129398..b7fb1e4 100644
--- a/node_modules/alasql/dist/alasql.fs.js
+++ b/node_modules/alasql/dist/alasql.fs.js
@@ -16739,10 +16739,14 @@ alasql.into.XLSX = function (filename, opts, data, columns, cb) {
 		var dataLength = Object.keys(data).length;
 
 		// Generate columns if they are not defined
-		if ((!columns || columns.length == 0) && dataLength > 0) {
-			columns = Object.keys(data[0]).map(function (columnid) {
-				return {columnid: columnid};
-			});
+		if ((!columns || columns.length == 0)) {
+			if (dataLength > 0) {
+				columns = Object.keys(data[0]).map(function (columnid) {
+					return {columnid: columnid};
+				});
+			} else {
+				columns = [];
+			}
 		}
 
 		var cells = {};
```

**Comment by mathiasrw** [comment]
Amazing. Thank you! Would you like to edit the file and make a pull request so your name is tracked as a contributer, or are you ok with me just applying the patch?

**Comment by gkkachi** [comment]
@mathiasrw 
I have made a pull request #1872 , which contains the patch above and a test to reproduce the error.
