### ISSUE TITLE
Property 'Database' does not exist on type 'AlaSQL'.

### ISSUE THREAD

**Issue by mateja176** [AlaSQL/alasql#1180]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Question about how to ...
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something is not working as expected:
- Describe the problem
  - TypeScript type error is thrown based on the lack of a type signature
- Provide code that replicates the problem 
  - https://stackblitz.com/edit/alasql-database-does-no-exist?file=index.ts

**Comment by rendall** [comment]
I address this with PR #1865

**Comment by mathiasrw** [comment]
Fix released as part of v4.2.6
