### ISSUE TITLE
npm test fails for current 'develop' branch

### ISSUE THREAD

**Issue by sethch** [AlaSQL/alasql#1190]
When running `npm test` on the current develop branch, the following error is output:

>   1) Test 251 Overwrite XLSX file
       1. Overwrite:
     SyntaxError: Invalid Unicode escape sequence
      at new Function (<anonymous>)
      at yy.Select.compile (dist\alasql.fs.js:8034:22)
      at Function.alasql.dexec (dist\alasql.fs.js:4654:38)
      at Function.alasql.exec (dist\alasql.fs.js:4622:17)
      at alasql (dist\alasql.fs.js:138:16)
      at Context.<anonymous> (test\test251.js:13:4)
      at processImmediate (internal/timers.js:456:21)

The offending line: 

```javascript			
alasql('SELECT HOUR(NOW()), MINUTE(NOW()), SECOND(NOW()) \INTO XLSX("' +
    __dirname +
    '/restest251.xlsx",{sourcefilename:"' +
    __dirname +
    '/test251.xlsx", \sheetid:"test2", range:"B3"})',
    [],
    function(res) {
	assert(res == 1);
        done();
    }
);
```

The issue seems to be `__dirname`, which is defined above the test case like:
```javascript
if (typeof exports === 'object') {
	var assert = require('assert');
	var alasql = require('..');
} else {
	__dirname = '.';
}
```

**Comment by mathiasrw** [comment]
Hmm. Interesting. Thank you for letting us know.

**Comment by mathiasrw** [comment]
@pasagedev Thank you _so_ much for looking into this. 

Any suggestion on how to avoid this?

**Comment by pasagedev** [comment]
> @pasagedev Thank you _so_ much for looking into this. 
> 
> Any suggestion on how to avoid this?

I'm trying to follow the flag `sourcefilename` to see where is the problem but It's hardest for me because I don't understand how work everything.
However I known than XLSX function get malformed path arg when is called and there's a function `toString` than change double backslash (`\\`) for single backslash when return the value. It could be the problem but I didn't can move on more.
