### ISSUE TITLE
AlaSQL pre-compressed with Brotli:11 on open source CDN

### ISSUE THREAD

**Issue by praisedpk** [AlaSQL/alasql#1206]
I have added AlaSQL on PageCDN. Current size of [alasql.min.js](https://pagecdn.io/lib/alasql/v0.6.1/alasql.min.js) on PageCDN is just **72 KB** that is around 12 KB smaller than normal due to better compression. The files are available on CDN here: https://pagecdn.com/lib/alasql

Adding this CDN link on download page is helpful for users looking to reduce JS size. If you allow, do I proceed with a PR to add it to installation section?

Thanks.

**Comment by mathiasrw** [comment]
Interesting. How are the files updated?

**Comment by praisedpk** [comment]
Currently it pulls files from this GitHub repo periodically. However, it is possible to send updates in real time using a webhook. If you are willing, I can send the webhook URL in private.

It is also possible to link to the latest version of the URL by replacing the version number with the keyword 'latest' in CDN URL, like [this](https://pagecdn.io/lib/alasql/latest/alasql.min.js).

Does that answer your question?

**Comment by mathiasrw** [comment]
Oh. For it to be part of the formal documentation we need it to fetch the files from the latest release. That can be a release on github or npm - but fetching from the repo "sometimes" will lead to them having a version that is not released yet. Is that something we can work on?

**Comment by praisedpk** [comment]
Yes, we can do this via GitHub hooks if this is workable for you.

**Comment by mathiasrw** [comment]
Im glad that you share the code in a smaller format, but for this to work we need pagecnd to tap into the published npm package (like most other platforms). At the moment the build is in the repo, but this will change soon.

**Comment by praisedpk** [comment]
Ok. We can work on it. Will update this thread in few days.

Thanks.

**Comment by praisedpk** [comment]
Done. It now pulls from npm in real time. Here are the files: https://pagecdn.com/lib/alasql

    https://pagecdn.io/lib/alasql/{version}/alasql.min.js
    https://pagecdn.io/lib/alasql/0.6.2/alasql.min.js

**Comment by mathiasrw** [comment]
Lovely!
