### ISSUE TITLE
Follow Redirect

### ISSUE THREAD

**Issue by jobdiogenes** [AlaSQL/alasql#1207]
I'm using alasql to get CSV data from Google Sheets.
It's works ate first time, but, after a time, stop to works,
I use curl to test url, and find that  Google,  make temporary redirect (HTML text response exactly this).
Then using curl to follow redirects, works.
But, alasql, seems to not follow redirects. 
Would be nice to have an options {followredirect:true}, as parameters, when using web url.
to CSV, TSV, ...

`
const sheetID = "put your google sheet id here";
const csvURL = "https://docs.google.com/spreadsheets/d/"+sheetID+"/export?format=csv&gid=0";
alasql.promise('SELECT * FROM CSV("'+csvURL+'",{headers:true})');
`

Thanks

**Comment by mathiasrw** [comment]
Interesting. 

Not sure its an issue with alasql. Is it node or browser you are using?

**Comment by jobdiogenes** [comment]
> Interesting.
> 
> Not sure its an issue with alasql. Is it node or browser you are using?

In browser.

**Comment by mathiasrw** [comment]
Hmm. Tests are working. Can you come with a sheetId that is not working?
