### ISSUE TITLE
Generated xlsx file with column range out of bounds

### ISSUE THREAD

**Issue by islotwin** [AlaSQL/alasql#1350]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

**Problem**: Generated xlsx file in alasql has more columns in range than actual data. The same file passed through another program (i.e. google docs) returns right number of columns. 
I think it comes from the fact, that in alasql columns are indexed starting with `0` (https://github.com/agershun/alasql/blob/develop/src/15utility.js#L1153). However, the end range is calculated basing on `columns.length` (https://github.com/agershun/alasql/blob/develop/src/833xlsx.js#L123). So, end range is actually out of bounds. Is it intended behavior?

**Example**: For file with data in columns "A" and "B" expected range would be "A:B". Received range is "A:C".

**Reproduction**: https://jsfiddle.net/mujsr8zy/6/

**File passed through google spreadsheets**: [example-2.xlsx](https://github.com/agershun/alasql/files/6709093/example-2.xlsx)

**Comment by mathiasrw** [comment]
Released as part of https://github.com/AlaSQL/alasql/releases/tag/v2.0.1
