### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by Gregory-Han** [AlaSQL/alasql#1399]
Hi, Team.

var res = alasql("SELECT SUM([SaleAmt]) AS [SaleAmt],COUNT(*) AS data_cnt 
FROM ? 
WHERE 
[typeNm] != 'cash' 
AND [saleQty] > 20000 
AND [SaleAmt] = 1 
HAVING SUM([SaleAmt]) BETWEEN 1 AND 10000" ,[data]); 

It happend script error.

**Comment by mathiasrw** [comment]
What is the error?

**Comment by jimmywarting** [comment]
erm... if you want multi line strings then you better use backticket `` ` ``

```diff
- var res = alasql("SELECT SUM([SaleAmt]) AS [SaleAmt],COUNT(*) AS data_cnt
+ var res = alasql(`SELECT SUM([SaleAmt]) AS [SaleAmt],COUNT(*) AS data_cnt
FROM ?
WHERE
[typeNm] != 'cash'
AND [saleQty] > 20000
AND [SaleAmt] = 1
- HAVING SUM([SaleAmt]) BETWEEN 1 AND 10000", [data]);
+ HAVING SUM([SaleAmt]) BETWEEN 1 AND 10000`, [data]);
```

this was asked a year ago, doubt that this is still relevant? close maybe?
