### ISSUE TITLE
Undocumented behavior in crontab for alasql cli

### ISSUE THREAD

**Issue by landall** [AlaSQL/alasql#1405]
I use alasql-cli in crontab but find it cannot accept a SQL statement ('No sql to process') when I write
`/usr/local/bin/alasql "SELECT author,count(1) as c into JSON(\"${YLOG}\") from CSV(\"${DLOG}\") where timestamp=$yesterday group by author order by author asc"`

but can work in pipe mode.
`echo "SELECT author,count(1) as c into JSON(\"${YLOG}\") from CSV(\"${DLOG}\") where timestamp=$yesterday group by author order by author asc" | /usr/local/bin/alasql`

I guess it is caused by Boolean(process.stdin.isTTY) in /usr/local/bin/alasql, but i do not know how to fix it.

OS: AlmaLinux 8.4
node: v16.8.0
SELinux: Enforcing

**Comment by mathiasrw** [comment]
Good point. If you run that command wrapped in another execution it will not try to read the parameter as SQL. Let me fix that.

**Comment by mathiasrw** [comment]
Released as part of v2.0.2
