### ISSUE TITLE
UNION not returning correct result

### ISSUE THREAD

**Issue by umquat** [AlaSQL/alasql#1415]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Question about how to ...
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something is not working as expected:
- Describe the problem  

    UNION does not work.

- Provide code that replicates the problem 
```
data1=[{a:'abc'},{a:'xyz'}]
data2=[{a:'123'},{a:'987'}]

alasql("select * from :a union select * from :b",{a:data1,b:data2})

```
--- FF 95.01 Linux
```
[
  {},
  {},
  {
    "a": "abc"
  },
  {
    "a": "xyz"
  }
]

```
alasql.version
"1.7.3-develop-0be167bcundefined"

----- Chrome 97.0 Linux
```

[
    {},
    {},
    {
        "a": "abc"
    },
    {
        "a": "xyz"
    }
]
```
alasql.version
'1.7.3-develop-0be167bcundefined'

---- Node
```

> data1=[{a:'abc'},{a:'xyz'}]
[ { a: 'abc' }, { a: 'xyz' } ]
> data2=[{a:'123'},{a:'987'}]
[ { a: '123' }, { a: '987' } ]
> 
> alasql("select * from :a union select * from :b",{a:data1,b:data2})
[ {}, {}, { a: 'abc' }, { a: 'xyz' } ]
> alasql.version
'1.7.3-develop-0be167bcundefined'

```

---- How does it work in sqlite3

```
sqlite> create table one(a text);
sqlite> create table two(a text);
sqlite> insert into a values('abc'),('def');
sqlite> insert into two values('xyz'),('123');
sqlite> select * from one union select * from two;
123
abc
def
xyz


```

- We suggest to spawn a jsfiddle from http://jsfiddle.net/98qL7m0c/

----

Maybe I'm using alasql incorrectly? I tried looking at some documentation in the wiki but the section on union is quite spartan.

Anyway, thanks a lot!

**Comment by mathiasrw** [comment]
It should work - but does not...

**Comment by Tisamu** [comment]
I would like to take the issue, could it be assigned to me ? 👍 
( Here is a correct jsfiddle relative to this issue btw : http://jsfiddle.net/7pdhe9ng/ )

Thanks !

**Comment by mathiasrw** [comment]
Sure!

**Comment by mathiasrw** [comment]
@Tisamu Any ideas on how to approach this issue?

**Comment by Tisamu** [comment]
Hello, sorry for giving no news.

Yep I've debugged a bit and it seems that the params of the first table are not passed to the union compilation method.

I'm still trying to understand all the compilation process of the query so I'm not sure where is the problem precisely.

I'm gonna work more on it this weekend. 😄

**Comment by mathiasrw** [comment]
I have not dived into where this might be - but a few hints to debug: Its often good to understand the compiled function that is constructed to execute the query. 

Idea: 

Replicate the problem in the CLI version of alasql. 
```
node bin/alasql-cli.js 'select * from @[{x:true}, {x:3}] UNION select * from @[{x:false}, {x:9}]'
[
  {},
  {},
  {
    "x": true
  },
  {
    "x": 3
  }
]
```

In the file `dist/alasql.fs.js` >THIS FILE WILL BE OVERWRITTEN IF YOU `yarn build` OR `yarn test`!< you find where the compiled function to be executed is created. 

It could be here forexample

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/1063454/198262329-e51ce065-1430-4a5b-8a32-b27896458907.png">

Then you run your CLI command with the inspect flag

    node --inspect-brk bin/alasql-cli.js 'select * from @[{x:true}, {x:3}] UNION select * from @[{x:false}, {x:9}]'
    
 Then you open chrome and go to `chrome://inspect/#devices` and click "inspect"

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1063454/198262899-5f0e3677-a2cc-480c-a927-d27e578062ed.png">

Now click here to start running

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1063454/198263148-24319a7a-9cfe-4c21-a409-ea822f0833ae.png">


Then - if you placed the `debugger;` correctly you can inspect and follow what is happening. Happy hunting. 

(nope - the place I inserted the `debugger;` did not stop the execution meaning that its not the right place...)


---

Please remember to move any changes to the proper files in src/ folder. Too many times have I found a fix and forgot I was live editing in the build destination and had to redo the details.

**Comment by Tisamu** [comment]
Nice ! Thanks for the tips. 😄

**Comment by Tisamu** [comment]
Well, sorry but I've a bit busy those weeks, not sure if I will be able to fix it soon. :frowning_face: 

Feel free to un-assign me the issue if someone else wanna take it.

**Comment by mathiasrw** [comment]
Thank you for leaning in. Let me know if you leant something you want to share with others.

**Comment by mathiasrw** [comment]
Any luck @Tisamu  ?
