### ISSUE TITLE
IFNULL(a, b) returns b for falsy a values

### ISSUE THREAD

**Issue by leobia** [AlaSQL/alasql#1433]
Something is not working as expected:
- The function `IFNULL(a,b)` returns `b` even for all falsy JS values

An example of the bug can be found here: [http://jsfiddle.net/leobia/gkdo7zjw/](http://jsfiddle.net/leobia/gkdo7zjw/)

**Comment by mathiasrw** [comment]
Released as part of https://github.com/AlaSQL/alasql/releases/tag/v2.0.1
