### ISSUE TITLE
IS NOT TRUE not works properly

### ISSUE THREAD

**Issue by baramofme** [AlaSQL/alasql#1466]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Expect

0 IS NOT TRUE => TRUE
1~100 IS NOT TRUE => FALSE

Because, in MySQL IS CHECKS value is 0 or NOT...

Something is not working as expected:

    >console.table(alasql('SELECT TRUE IS NOT TRUE, TRUE IS NOT FALSE'))
    ┌─────────┬───────────────────┬────────────────────┐
    │ (index) │ TRUE IS NOT(TRUE) │ TRUE IS NOT(FALSE) │
    ├─────────┼───────────────────┼────────────────────┤
    │    0    │       true        │        true        │
    └─────────┴───────────────────┴────────────────────┘

    TRUE IS NOT TRUE should be FALSE. 

    >console.table(alasql('SELECT 0 IS NOT TRUE, -1 IS NOT TRUE, 1 IS NOT TRUE'))
    ┌─────────┬────────────────┬─────────────────┬────────────────┐
    │ (index) │ 0 IS NOT(TRUE) │ -1 IS NOT(TRUE) │ 1 IS NOT(TRUE) │
    ├─────────┼────────────────┼─────────────────┼────────────────┤
    │    0    │      true      │      true       │      true      │
    └─────────┴────────────────┴─────────────────┴────────────────┘
    
    1 IS NOT TRUE shoudl be FALSE,
    except 0 every other number should be treated as TRUE So, 1 IS NOT TRUE should be FALSE,

**Comment by mathiasrw** [comment]
Released as part of v2.1.6
