### ISSUE TITLE
[Typescript] userDefinedFunction

### ISSUE THREAD

**Issue by leqwasd** [AlaSQL/alasql#1467]
Typings for userDefinedFunction (used in `alasql.fn.<fnName> = <here>`)

should be
```diff
	interface userDefinedFunction {
-		(x: any): any;
+		(...x: any[]): any;
	}
```
It still doesn't provide any strong typings, but it would allow multiple arguments for a function.

**Comment by mathiasrw** [comment]
Released as part of v2.0.2
