### ISSUE TITLE
Filter JSON Data with sub array elment

### ISSUE THREAD

**Issue by GauravAshara** [AlaSQL/alasql#1483]
I have two dimensions arrays, So I want to filter each element's second subelement. 

Suppose I have the following data 
```
var data =[{
        name : "1",
        p :[["Data1","IRA","Data2"],["Data4","USA","Data5"]]
        },
        {
        name : "2",
        p :[["Data5","FRA","Data6"],["Data7","IND","Data8"]]
        }];   
        
```

I want filter data 
P->Arrays->[1] IN ("INR","USA")
var SQL =  "SELECT p FROM ?   ";        
So my out will be like 
["Data4","USA","Data5"]
["Data7","IND","Data8"]

**Comment by mathiasrw** [comment]
Use `.sort()` on the data array after to get the right sorting.
