### ISSUE TITLE
Unable to query sub level array element

### ISSUE THREAD

**Issue by pradeep-nagarajan** [AlaSQL/alasql#1492]
Unable to query sub level array element

    var data = [
      {
        myName: '1212',
        childData: {
          field1: 'test',
          field2: ['1', '2', '3', '4']
        }
      },
      {
        myName: '3333',
        childData: {
          field1: 'test2',
          field2: ['111', '22', '333', '444']
        }
      }
    ];

var res = alasql(`SELECT * from ? where childData->field2 = '333'`, [data]);
console.log(JSON.stringify(res));

**Comment by mathiasrw** [comment]
SQL is not made for this. Do a Map of the array.

**Comment by bnilesh** [comment]
@mathiasrw - do you have any example for this? I am running into similar scenario where I have build dynamic SQL query with WHERE IN clause.

```
var data = [
  {
    myName: '1212',
    childData: {
      field1: 'test',
      field2: ['1', '2', '3', '4']
    },
   hobbies : ['running', 'walking']
  },
  {
    myName: '3333',
    childData: {
      field1: 'test2',
      field2: ['111', '22', '333', '444']
    }
   hobbies : ['singing', 'walking']
  }
];
```
Q1 - 
var res1 = alasql(SELECT * from ? where childData->field2 in ('111', '333'), [data]);
console.log(JSON.stringify(res1));

Q2 - 
var res2 = alasql(SELECT * from ? where hobbies in ('walking', 'dancing'), [data]);
console.log(JSON.stringify(res2));
