### ISSUE TITLE
找到多个 azurlane 包，自动检测包 无法决定选择哪个，请复制其中一个可用设备 

### ISSUE THREAD

**Issue by Assrain** [AlaSQL/alasql#1507]
CRITICAL 15:54:19.572 │ Multiple azurlane packages found, auto package detection   
         cannot decide which to choose, please copy one of the available devices   
         listed above to Alas.Emulator.PackageName                                 
CRITICAL 15:54:19.574 │ Request human takeover

**Comment by mathiasrw** [comment]
Huh?
