### ISSUE TITLE
Uncaught exception when calling await alasql.promise("SELECT .. FROM xlsx(...)") with invalid filename

### ISSUE THREAD

**Issue by rein-dc** [AlaSQL/alasql#1519]
I'm having trouble getting exceptions to bubble up correctly when calling xlsx in async/promise mode. Not sure if this is really a bug or something I am doing wrong

A good example is passing an invalid Excel filename

In 84from.js, it seems that the cb arg to alasql.utils.loadBinaryFile() might be part of the problem. If I simply hardcode the param to 'false' (see attached) it works. I got this idea from looking at the call to 93sqljs.js line 31 which hardcodes to true (see attached). Alternatively, '!cb' instead of '!!cb' seems to work as well. Clearly they can't all be correct 

Note that there is also a call in 833xlsx.js (assuming the extension is exactly "xlsx"). Forcing a sync read is probably the only way to detect a bad filename

I cloned the code today so the below screenshots are on tag 2022-10-06

![Screen Shot 2022-10-07 at 17 15 02](https://user-images.githubusercontent.com/16494473/194574646-a3dcfeca-68a6-47ba-822c-2c8bcc1ea3c9.png)

![Screen Shot 2022-10-07 at 17 19 34](https://user-images.githubusercontent.com/16494473/194575686-502069d8-6e10-4ae7-b792-e4c7dead5425.png)

This is what my original call looks like (it's in a retry loop)
![Screen Shot 2022-10-07 at 17 30 53](https://user-images.githubusercontent.com/16494473/194578229-5bc76bde-4aab-42c4-8ad7-b7829c69451a.png)

**Comment by mathiasrw** [comment]
Good point. Lots of things missing regarding error handeling when reading files. Released as part of v2.1.4. Please verify that its working now.

**Comment by mathiasrw** [comment]
@rein-dc ?
