### ISSUE TITLE
Will loading alasql-worker.js automagically be used when using alasql through npm package (React app)?

### ISSUE THREAD

**Issue by thekennysong** [AlaSQL/alasql#1521]
- Describe the problem  

I am not sure whether or not the web workers are working properly while using 

`<script src="https://cdn.jsdelivr.net/npm/alasql@0.4/dist/alasql-worker.js"></script>`

in my React project. How do I verify the web workers are being used?

- Provide code that replicates the problem 

I am importing the above and then using `alasql` in my React project. More specifically:
` "alasql": "^0.6.5",`

**Comment by mathiasrw** [comment]
If you are including the webworker scripts after the alasql script it works if you dont get this error message

![image](https://user-images.githubusercontent.com/1063454/195249756-606901c2-8f00-4de7-975b-9267e12a0401.png)
