### ISSUE TITLE
SUM for only NULL values

### ISSUE THREAD

**Issue by mathiasrw** [AlaSQL/alasql#1533]
_Spawn from https://github.com/AlaSQL/alasql-sqllogictest/blob/a10ff82e75edafae2ce96c9d02ab47cfc85d4507/results/output.md#3620-testevidenceslt_lang_aggfunctest_

    SELECT sum(x) FROM t1 WHERE y='null'

    Expected: ["NULL"] but got ["0"]

> If there are no non-NULL input rows then sum() returns NULL but total() returns 0.0

**Comment by gangadhargo** [comment]
Hi @mathiasrw 

I tried to fix these issues. would you please verify my PR once?
https://github.com/AlaSQL/alasql/pull/1537

Thanks
Ganga.

**Comment by mathiasrw** [comment]
Uhh!

**Comment by mathiasrw** [comment]
Released as part of v2.2.0
