### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LalithaSJyothi** [AlaSQL/alasql#1552]
Hi AlaSQL Team .. I am facing this error while using REPLACE in select query ... (e || "").split is not a function ... my query is select product, expressions, REPLACE(field_names,'file','xx') from {{ResultValidationMapping.data}}

**Comment by mathiasrw** [comment]
Hi 

For me to help out I will need. you to provide code that replicates the problem 

I suggest to spawn a jsfiddle from http://jsfiddle.net/98qL7m0c/
