### ISSUE TITLE
create indexeddb table never runs callback

### ISSUE THREAD

**Issue by jimmywarting** [AlaSQL/alasql#1577]
http://jsfiddle.net/Lcmkyfxe/

I'm debugging some browser test and one thing is timing out...
more specifically: 
```js
alasql('CREATE IndexedDB DATABASE ag154', [], () => {
  // this never runs...
})
```

Here is what i think happens:

https://github.com/AlaSQL/alasql/blob/f7984eab8862988ab815443fd0163d1a49b6f9d3/src/91indexeddb.js#L92-L97

1. `onupgradeneeded` is executed
2. the transaction gets aborted.
3. `request1.onabort` never gets called... (?)
4. an error is thrown but there is nothing that catches it... there are not any `request1.onerror`...
5. so no callback is executed.

I also notices that there are some throw exceptions... do they really work as they should?
shouldn't it be executing a callback?
I'm not sure what callback style you are using, it ain't like nodejs convention like `cb(err?, res)`
seems to be `cb(res?, err)`

I suppose this:
https://github.com/AlaSQL/alasql/blob/f7984eab8862988ab815443fd0163d1a49b6f9d3/src/91indexeddb.js#L98-L104
should be more like this?
```js
request1.onsuccess = function (event) { 
  event.target.result.close()
  cb(null, new Error(`IndexedDB: Cannot create new database "${ixdbid}" because it already exists`))
}
```

**Comment by jimmywarting** [comment]
Oh, btw... i'm testing chrome.

**Comment by jimmywarting** [comment]
in fact abort dose not exist...
![image](https://user-images.githubusercontent.com/1148376/208264047-935dc2e7-bf17-4e7d-b9a5-dae60fd557dd.png)

**Comment by mathiasrw** [comment]
The code for indexedDB is really old. Happy to adapt to the style you find most useful for error handling. 

One input: I propose that next large version of alasql removes support for providing functions for callback, and move towards all calls returning a promise (as default - and an option to run some calls as sync that just throws an error) so maybe dont rethink the full error return flow for now.

**Comment by jimmywarting** [comment]
Hmm, usually promises are a bit slower than callbacks

And other indexeddb libraries like dexie use some Promise A/+ library that so happens to be sync instead of async.
That allows them to write more performant transactions. b/c when you wait for some async promise to be resolved then you will have already closed the transaction and can't continue some operations.

but i skimmed through the IndexedDB spec and there seem to be some new features about manually controlling commits and allowing transactions to stay open until you say it's done with some kind of ExtendableEvent with `evt.waitUntil`?

but i agree, promises are nicer. 

ideally two queries that both do a insert should only have to open the database once and complete it in one transaction?
