### ISSUE TITLE
Poor error handling with bad "order by"

### ISSUE THREAD

**Issue by peterbe** [AlaSQL/alasql#1588]
```sql
SELECT title, length(title) AS length FROM ? ORDER BY 3 DESC LIMIT 10
```
https://jsfiddle.net/peterbe/rsxdona9/3/

I, now, appreciate my error. You can't order by the 3rd column, if there isn't one. But it's a human error and happened in production and will happen again. The error handling itself seems to fail:
```
TypeError: Cannot read properties of undefined (reading 'toJS')
```
I would much prefer if it said:
```
The "order by" number is wrong. Selected only 2 columns, so can't order by the third
```
:)

**Comment by mathiasrw** [comment]
Fix released as part of v2.2.5
