### ISSUE TITLE
Import "cd/alasql.js" need to update alasql to be used as es6 library

### ISSUE THREAD

**Issue by AjManoj** [AlaSQL/alasql#1592]
AlaSQL is based on unpaid voluntary work. Thank you for taking the time to make it better. 

Question about how to ...
- Please use http://stackoverflow.com/questions/ask?tags=alasql

Something is not working as expected:
- Describe the problem  
- Provide code that replicates the problem 
- We suggest to spawn a jsfiddle from http://jsfiddle.net/98qL7m0c/

**Comment by mathiasrw** [comment]
Yes. AlaSQL is not an WS6 library yet. We are working on it. Closing.
