### ISSUE TITLE
IndexedDB is not working with iOS

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#16]
The reason: Alasql uses Chrome's specific function indexedDB.webkitGetDatabaseNames().
This function is not critical, and can be modeled with openDatabase().

**UPDATE**
The same problem with Firefox

**Comment by agershun** [comment]
This bug was related to this issue:

https://github.com/agershun/alasql/issues/126

But it still was not solved.

**Comment by mathiasrw** [comment]
Has  `indexedDB.webkitGetDatabaseNames()` been changed to `openDatabase()` ?

**Comment by jimmywarting** [comment]
> Has `indexedDB.webkitGetDatabaseNames()` been changed to `openDatabase()` ?

Yes it has. I'm not sure if this is a problem anymore. 
if it's doing some conditional check or something.

but at least my PR: #877 should at least cover this issue if it's not already solved.
so i think this can be closed
