### ISSUE TITLE
NPM version is wrong

### ISSUE THREAD

**Issue by jcubic** [AlaSQL/alasql#1601]
I've started working on the SQL terminal, I was not able to find the proper file, but there is a problem because alasql.version on NPM is from develop (and has git commit):

![ala-sql](https://user-images.githubusercontent.com/280241/209863254-b67cfa25-ac89-4f1d-9633-cc4238a4c4a3.png)

I've used: https://cdn.jsdelivr.net/npm/alasql/dist/alasql.min.js

**Comment by mathiasrw** [comment]
Thank you for the input. Not good.

I propose you use 
    <script src="https://cdn.jsdelivr.net/npm/alasql@2"></script>

**Comment by jimaek** [comment]
jsDelivr also has a purge API you could use as part of your release workflow to avoid outdated versions completely https://github.com/jsdelivr/jsdelivr#purge-cache

**Comment by mathiasrw** [comment]
Oh - interesting. Thanks.

**Comment by jcubic** [comment]
`https://cdn.jsdelivr.net/npm/alasql@2` gives the same version:

```javascript
D.version="2.2.4-develop-d97ae856"
```

I think that the latest version is wrong. You probably published a develop version to NPM.

**Comment by mathiasrw** [comment]
Ahh - I get it now. Nope. Its correct. The version string is the version from npm, the branch it was compiled from and the active commit

**Comment by jcubic** [comment]
So if the version is correct does it mean that you no longer use semver for versions? The variable is kind of useless then if it doesn't contain the version number.

**Comment by jcubic** [comment]
My understanding of version number is when I use @2.0.1 as a tag from CDN the version variable in the code should be 2.0.1 and not have git commit and develop marker. Because if it doesn't it look like it was published from the devel branch and not a real release.

**Comment by mathiasrw** [comment]
Adding meta data about the build is perfectly valid for sermver versioning according to https://semver.org

<img width="919" alt="image" src="https://user-images.githubusercontent.com/1063454/210025642-635fac88-7f9b-4951-9dc2-ec369b93f64a.png">

**Comment by jcubic** [comment]
Ok if this is ok then why NPM version doesn't have the same tags? Why this doesn't work:

https://cdn.jsdelivr.net/npm/alasql@2.2.5-develop-63c84c04

You have two completely different versions one for NPM and one for code that is tasked from devel branch. But if you think this is ok then I don't have any more questions. But you can't really use the version from the code because it's not the real version on NPM.

**Comment by mathiasrw** [comment]
Hmmm.

**Comment by jcubic** [comment]
Just to give an argument I use the version variable in jQuery Terminal to show the current version of the library:

![Screenshot of Web-Based Terminal](https://user-images.githubusercontent.com/280241/210170617-ab6c7e33-8fca-4a46-8a51-29a288275acc.png)

And this is what I wanted to put into AlaSQL REPL. If the version has a devel suffix it doesn't look nice and you can't actually use it for anything. It's as good as no version at all.

**Comment by mathiasrw** [comment]
Released as part of v2.5.0
