### ISSUE TITLE
SQL Keywords Page Dead Link

### ISSUE THREAD

**Issue by Nosam55** [AlaSQL/alasql#1602]
On the [SQL keywords](https://github.com/alasql/alasql/wiki/SQL%20keywords) wiki page, the link on the word "here" in "(based on the table from **here**)" now links to a 404 Not Found.

I recommend the link address be changed to the last archive.org cache of the site, which can be found [here](https://web.archive.org/web/20170427161717/http://developer.mimer.com/standard/reservedwords/sql-reserved-words.tml):

```
https://web.archive.org/web/20170427161717/http://developer.mimer.com/standard/reservedwords/sql-reserved-words.tml
```

**Comment by mathiasrw** [comment]
Done. Thank you!
