### ISSUE TITLE
WebSQL will be removed from chrome.

### ISSUE THREAD

**Issue by sayami007** [AlaSQL/alasql#1625]
Currently, AlaSQL is using WebSQL in its code. However, chrome is going to drop the WebSQL support. 
https://developer.chrome.com/blog/deprecating-web-sql/

Should we be stop using AlaSQL?

**Comment by mathiasrw** [comment]
Fix released as part of v3.0.0

**Comment by sayami007** [comment]
Great, Thanks 👍👍
