### ISSUE TITLE
SUM(FUNC(x)) is BROKEN since 2.2.0

### ISSUE THREAD

**Issue by phantasma2983** [AlaSQL/alasql#1666]
Tested SUM(FLOOR(col) and it is not running FLOOR or CEIL or ROUND or anything inside SUM ever since version 2.2.0 release.
It's working fine in 2.1.8 all versions after that are not working for this use-case.

**Comment by mathiasrw** [comment]
omg. I dont know how I missed this issue! - this is huge!

Thank you for letting us know!!!

**Comment by Shibn2** [comment]
If the issue is still not fixed, I 'd like to contribute @mathiasrw

**Comment by NmN03jain** [comment]
in this issue we have to make changes every place where sum is used ?

**Comment by mathiasrw** [comment]
I am not sure. I have not looked into it.

**Comment by rrameshkumar76** [comment]
@mathiasrw  I took a quick look at this (https://github.com/rrameshkumar76/alasql/pull/1/files?diff=unified&w=1) , Have an slight idea for a fix based on my limited understanding.  I am having issue with one test using tables and spy(https://github.com/AlaSQL/alasql/blob/develop/test/test020.js#L67).  

I am little unclear with this https://github.com/AlaSQL/alasql/blob/develop/test/test020.js#L53C3-L53C30 used in spec when the spy function is expected to be used or not in the various test criteria used in that test. I have changed those tests based on my understanding of whats correct.

I will have to add a much better tests also.

I also think some fix has to be done for MIN, MAX etc also afaict. I am trying those also in above,

**Comment by rameshrajagopalanbayer** [comment]
I also think some fix has to be done for MIN, MAX etc also afaict. I am trying those also in above,

**Comment by mathiasrw** [comment]
> when the spy function is expected to be used or not 

The spy function is just a random name for a custom function. Maybe I did not understand your doubt. Please ask again so we can progress together.

**Comment by rrameshkumar76** [comment]
Thanks, yeah thats what I thought too on the name spy was not anything special.  I forgot to properly edit my comments above. Sorry about that.

I will create a PR for above

**Comment by rrameshkumar76** [comment]
@mathiasrw  I have opened a PR https://github.com/AlaSQL/alasql/pull/1788 for discussion. Please take a look and see if this is fine or let me know of changes if any needed for this.
