### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive

### ISSUE THREAD

**Issue by NikiLentz** [AlaSQL/alasql#1667]
Hi, 
I am currently working on a small electron app and trying to use alasql.

Currently i am just trying to read a csv file, I managed to get it working, but I had to add unsafe-eval to my csp, otherwise i got the exception in the title.

Can this be done without adding it, since I don't feel very comfortable adding unsafe-eval to a production app.

**Comment by mathiasrw** [comment]
Unsafe eval is deeply embedded in how alasql works - so this will keep being like this.

**Comment by githorse** [comment]
I'm also tripped up by this -- see [comment on #1482](https://github.com/AlaSQL/alasql/issues/1482#issuecomment-1952574066).
