### ISSUE TITLE
#doSearch breaks stencil js rollup build

### ISSUE THREAD

**Issue by ThatScalaGuy** [AlaSQL/alasql#1728]
Hi,

I am using alasql in a Stencil component project. After updating alasql from 1.x to 4.x the build is not working anymore. 

`Rollup: Plugin Error
Unexpected token (5358:2) in /Users/sven/Projects/test/alas/node_modules/alasql/dist/alasql.js (plugin: commonjs, transform)`

The unexpected token is the `#` in 35search. What is the # good for? 

https://github.com/AlaSQL/alasql/blame/eaa0b902eccb219ad3fb9df72a0c468abada2571/src/35search.js#L50

**Comment by jimmywarting** [comment]
Certainly! In JavaScript, the `#` symbol is used to denote private class fields. It was introduced in ECMAScript 2019 (ES2019) as part of the ES6 (ECMAScript 6) specification.

A private class field is a class member that can only be accessed from within the class itself. It is not accessible outside of the class, including from instances of the class or other external code. This helps in encapsulating implementation details and provides a way to hide internal state or functionality of a class.

Here's an example to illustrate the usage of private class fields:

```javascript
class MyClass {
  #privateField;

  constructor() {
    this.#privateField = 10;
  }

  #privateMethod() {
    console.log('This is a private method.');
  }

  publicMethod() {
    console.log('This is a public method.');
    console.log(this.#privateField);
    this.#privateMethod();
  }
}

const myInstance = new MyClass();
myInstance.publicMethod(); // Output: This is a public method. 10 This is a private method.
console.log(myInstance.#privateField); // Error: SyntaxError: Private field '#privateField' must be declared in an enclosing class
myInstance.#privateMethod(); // Error: SyntaxError: Private field '#privateMethod' must be declared in an enclosing class
```
In the above example, the MyClass has a private field #privateField and a private method #privateMethod. These private members are denoted by the # symbol preceding their names.

Inside the class, the private field and method can be accessed just like any other class member. However, outside of the class, attempts to access the private members will result in syntax errors.

The # symbol is used to establish a convention that certain members of a class should be treated as private, indicating that they are intended for internal use and should not be accessed or modified directly from outside the class.

---

all green env / browser supports this today, but old build system might not... it might be worth it if you update your own dependencies.
