### ISSUE TITLE
LIKE will not work correctly when there is a line break

### ISSUE THREAD

**Issue by Ztengchao** [AlaSQL/alasql#1734]
Run this code on [RunKit](https://npm.runkit.com/alasql)
Example Code:
```JavaScript
var alasql = require("alasql")
var data = [ {a: 'Lorem \n\r ipsum'} ];
var res = alasql('SELECT a FROM ? WHERE a LIKE "Lorem%"',[data]);
```
Expect Output:
> [{a: "Lorem \n\r ipsum"}]

Actual Output:
> []

When I change code to this, It output correct result:
```JavaScript
var alasql = require("alasql")
var data = [ {a: 'Lorem \n\r ipsum'} ];
var res = alasql('SELECT a FROM ? WHERE REPLACE(REPLACE(a, CHAR(13), ""), CHAR(10), "") LIKE "Lorem%"',[data]);
```

**Comment by mathiasrw** [comment]
Ohhh. - good one!

**Comment by itsajay1029** [comment]
Can you assign this issue to me and explain on what needs to be done ? @Ztengchao

**Comment by Ztengchao** [comment]
> Can you assign this issue to me and explain on what needs to be done ? @Ztengchao

I don't have permission to assign issue and I don't know what needs to be done. @itsajay1029

**Comment by itsajay1029** [comment]
Can you explain me what I need to do here @mathiasrw ?

**Comment by this-is-sky** [comment]
> Can you explain me what I need to do here @mathiasrw ?

Hey, are you working on this? This issue seems interesting to me, so I want to work on this too.

**Comment by this-is-sky** [comment]
Hey @mathiasrw, can you please assign this issue to me also?

**Comment by rameshrajagopalanbayer** [comment]
Hi @mathiasrw  I can work on this and create a PR is no one else has yet gotten a chance to get around to this.

**Comment by mathiasrw** [comment]
How are you going with this @this-is-sky ? 

Should we hand it over to @rameshrajagopalanbayer

**Comment by rameshrajagopalanbayer** [comment]
@mathiasrw  I created https://github.com/AlaSQL/alasql/pull/1794 . Please take a look and let me know if this looks ok
