### ISSUE TITLE
Using with node.js

### ISSUE THREAD

**Issue by ravi-cogos** [AlaSQL/alasql#1749]
Hi Team,
Thanks for the wonderfull librarary.
I am trying to use alasql with expressjs running on v12. 
I installed the library as per the documentation and i am getting error when i try to import in my express js route and start the expressjs server.

Installation: **npm install --save alasql**
Import :  **var alasql = require('alasql');**

When I start my expressjs service I get the following error, 
![image](https://github.com/AlaSQL/alasql/assets/115131021/1df9934c-cef8-447a-8a44-1ff8d77fb633)

Could anyone help me to solve this.

Thanks,
Ravi

**Comment by ravi-cogos** [comment]
Hi Team,
I downgraded to alasql to version 2.0.1 it is working fine.

Thanks
Ravi

**Comment by mathiasrw** [comment]
For security reasons I urge you to upgrade your v12 environment.

See https://nodejs.dev/en/about/releases/
