### ISSUE TITLE
Modify AlaSQL to allow generate AST with other parsers (e.g. with Closure)

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#183]
Some people want to write their queries with other query languages than SQL. E.g. query can ve written on Closure, it will generate AST, and AlaSQL will execute it.

**Comment by mathiasrw** [comment]
I cant get my head around why that would be awesome. Maybe we could have some more words from the ones with the need. 

Idea: If we make the module system where we can select flavour of SQL - will it be a parser module that generates a AST for the "engine" ? If so, we have a way of people extending with their own "parser" or how ever they want to create their selection interface.

**Comment by mathiasrw** [comment]
Any inputs?
