### ISSUE TITLE
alasql.js vs alasql.core.js

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#190]
To minimize the size of core alasql browser version of AlaSQL will splitted on two different version:
- `alasql.js` - full version with all database backends, etc.
- `alasql.core.js` - minimal version, including only basic core functionality of SQL.

Probably in the future AlaSQL will have separate version without parser `alasql.exec.js`

**Comment by mathiasrw** [comment]
How much will we gain? when would it be OK just to use the core?

Introducing more options also introduces more confusion if we are not clear in our message of what to choose.

**Comment by agershun** [comment]
Now I compacted AlaSQL to 340kb, probably if we exclude some rare options, it will be less than 300 kb.
Even so, it may be too much to use it in mobile. For example Lovefield library now is about 130kb.
