### ISSUE TITLE
New alasql.org starting page

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#278]
@mathiasrw May I ask you to give a feedback on out next version of alasql.org start page?

http://alasql.org/codex/start.html

**Comment by mathiasrw** [comment]
Sure!!!

Im on my phone right now but will get back to you as soon as I reach a computer.

**Comment by sovanna** [comment]
I will give you a feedback when I get to simply execute "bower install alasql", for now, it simply failed with 

    bower alasql#*                  cached git://github.com/agershun/alasql.git#0.1.9
    bower alasql#*                validate 0.1.9 against git://github.com/agershun/alasql.git#*
    bower xlsx#0.8.0            not-cached git://github.com/stephen-hardy/xlsx.js.git#0.8.0
    bower xlsx#0.8.0               resolve git://github.com/stephen-hardy/xlsx.js.git#0.8.0
    bower js-xls#~0.7.5             cached git://github.com/SheetJS/js-xls.git#0.7.5
    bower js-xls#~0.7.5           validate 0.7.5 against git://github.com/SheetJS/js-xls.git#~0.7.5
    bower es6-promise#2.1.0         cached git://github.com/components/es6-promise.git#2.1.0
    bower es6-promise#2.1.0       validate 2.1.0 against git://github.com/components/es6-promise.git#2.1.0
    bower xlsx#0.8.0          ENORESTARGET No tag found that was able to satisfy 0.8.0

    Additional error details:
    No versions found in git://github.com/stephen-hardy/xlsx.js.git

**Comment by agershun** [comment]
@sovanna Sorry for this... I still do not understand the source of the problem . Lets continue in https://github.com/agershun/alasql/issues/271

**Comment by mathiasrw** [comment]
I have a lot of inputs - but only have time to write a few right now. 

- Really love all the energy you put into the welcome screen. 

- My general perception is that I miss the embracing arms of the old page promesing that here is something at good and awesome as space itself.


- Is the galaxy a theme we want to continue. I vote yay. I really miss the space theme on the exsisting page and by that the feeling of grandiosity. <br>(I actually had the idea of comming with a suggestion to an icon based on something like [this](https://cdn4.iconfinder.com/data/icons/unigrid-science/64/003_universe_galaxy_milky_way_milkyway_cosmos_macrocosm-512.png ) or in [colors](https://cdn3.iconfinder.com/data/icons/unigrid-flat-science/90/003_017_universe_galaxy_milky_way_milkyway_cosmos_macrocosm-512.png) representing AlaSQL as this gluing gravity center connecting your data with your questions )


- It confuses me that it says I can write both javascript and SQL. I tried this (valid js) and got a parsing error

```
/* Enter your code in SQL
 or JavaScript below */

4+6
```

- Im not sure we help on the first page by letting people mix javascript and SQL - its not intuitive. I recomend only javascript OR that you somehow say / show if this is javascript or SQL (lidt a little switch or a hamonica s you do at the example). But its a balance.... hmmm. thinking. 

- For big screens it feels strange that the page is full width. Maybe set a max width of the content to about 1200 -1500 px. Would be nice if the top was still blue full width :)

- Place a "its conna open another site" icon next to menu elements where it opens forexample github. 

- Have the gihub logo as icon. No reason to fill as a menu element


- Download could very well be to a page where they get a copy paste ready text to include in html from cdn. The page could also link to wiki section about use in node. There is also the whole "costum build" thing that would be good here. 

- It is very very important that the message about what this is gets transmitted. I feel the old front page did this better - now the interactive typewriter is the main thing (before it was the information)

- I love the typewriter - but when I click it to edit, the full example its writing must be there so I can edit the full example. Right now I have to wait until its done

- While typewriting we get really big nasty red compile errors - could we eleminate those while typewriting?

- There is something about the layout that not in. My personally favorit is nothing at the side, but big chuncky sections underneath (more like the exsisting site). This is not important (what I personally farvorite) but whats important is that we are giving people a good information flow to grasp the awesomeness the first time. 

- How many examples are there? maybe just write it as a comment in the example soruce. Also a name / title so I can see what is it we are trying to examplify

- Its confuing that I have a menu at the top saying "examples" but have buttons stating next and prev example. I actually had the impression the fist 2 seconds that I would go to examples when clicking next example.

- Would be delightfull if you changed the color of the buttons to the same color as the top row at the answers

- When go to examples I would expect same top menu as on the front page. 

Keep up the good work !

**Comment by agershun** [comment]
Wow! These are good directions for homework! THANK YOU!!!! 
I'LL BE BACK!

**Comment by agershun** [comment]
Great set of MySQL examples to be used as tests and start page (and Codex) samples:
http://www.artfulsoftware.com/infotree/queries.php

**Comment by mathiasrw** [comment]
The 2 links has the same content but structured in 2 different ways. 

I have contacted Artful software to hear how this could work. As they are trying to sell a book about the subject I suggested that we place a link underneath examples from their site. Lets see.

**Comment by agershun** [comment]
Takke Dem!

**Comment by mathiasrw** [comment]
?

**Comment by agershun** [comment]
Thank you! :+1:

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by mathiasrw** [comment]
Any plans on updating alasql.org ?
