### ISSUE TITLE
Test with Browserify and ES6

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#280]
We need to test AlaSQL with Browserify and ES6. Please, write here if you already have en experience in AlaSQL and Browserify and ES6.

**Comment by ad34** [comment]
I m trying to use it in my aurelia.io project, without success for the moment. when pack the sources (using webpack ) I got an error if I import the alasql module

**Comment by mathiasrw** [comment]
Please make a new issue where you state hos you importe the new module and make sure you follow the guidelines given on https://github.com/agershun/alasql#webpack-and-browserify
