### ISSUE TITLE
PIVOT

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#287]
My current project requires PIVOT statement. I also found question in StackOverflow with similar request:
http://stackoverflow.com/questions/30442969/group-by-in-angularjs. Are there any reasons to do not include it in AlaSQL?

**Comment by mathiasrw** [comment]
:+1:

**Comment by agershun** [comment]
I like ```PIVOT BY``` syntax proposed in this [SO](http://stackoverflow.com/questions/12287240/how-to-pivot-column-values-into-columns). It easier to read and easier to realize. Of course, standard syntax also to be supported.

**Comment by mathiasrw** [comment]
Love the syntax. We can even use the answer as base for the wiki about it

**Comment by mathiasrw** [comment]
Hmm. How will it work when there is more than 3 cols in the original select?

**Comment by agershun** [comment]
Yes, there are some problems with this syntax. Anyway I am close to finish with standard syntax. Hope, this will be the first step to micro-olap features, like MDX

Отправлено с iPhone

**Comment by agershun** [comment]
Another option: we can add pseudo-MDX syntax like:

SELECT ... ON ROWS, ... ON COLUMNS..., but it can interfere with AlaSQL JSON, because it used { } brackets.

Отправлено с iPhone

**Comment by agershun** [comment]
Some ideas on pivots from Postgres http://www.postgresql.org/docs/9.1/static/tablefunc.html
