### ISSUE TITLE
Exporting to Excel

### ISSUE THREAD

**Issue by destanoglu** [AlaSQL/alasql#408]
When I open the result excel file, I got the "We found a problem with some content in '****.xlsx'. Do you want us to try to recover as mush as we can? If you trust the source of this book, click Yes." warning. After clicking the Yes button, I can see the expected data. But this warning should not appear. Do you have any solution for this?

**Comment by mathiasrw** [comment]
Please provide some example code so we can help debugging

**Comment by feralanPaladin** [comment]
I am just trying your examples :)
http://jsfiddle.net/agershun/0xgfjcre/1/

**Comment by mathiasrw** [comment]
Hmm. 

What version of excel is it? On Mac or widows?

**Comment by feralanPaladin** [comment]
Excel 2013 on Windows 8.1

**Comment by mathiasrw** [comment]
Thanks. I don't have access to a windows 8 but should not affect it. I will look into it and get back to you

**Comment by feralanPaladin** [comment]
Thank you

**Comment by mathiasrw** [comment]
Hmm. It should work... Excel tells me that there is an error in `/xl/workbook.xml` - I have not found the cause yet... :-/
