### ISSUE TITLE
run alasql in nodejs vm

### ISSUE THREAD

**Issue by xlvector** [AlaSQL/alasql#451]
We found there is some problems about run alasql in nodejs vm, this is mainly because of this issue.

https://github.com/nodejs/node-v0.x-archive/issues/1277

In alasql, there is many line like (x instanceof Array) to check if x is an array, and the better way is Array.isArray(x).  Use (x instanceof Array) will cause some problem when running alasql in vm.

For example, in prepareFromData() function.

**Comment by agershun** [comment]
Thank you! What is the best replacement for ```x instanceof Array``` in this case?

**Comment by mathiasrw** [comment]
> Array.isArray() is the best way to test if something is an array

So we can replcae with `Array.isArray( ... )` - but I dont know if this solves the core of the problem - that we cant rely on any ìnstanceOf`

**Comment by xlvector** [comment]
Yes, this does not solve the core problem. The core problem is "require" method is passed from main context to vm context so objects in alasql is not created by vm context.

following is implement of instance of in js:

function instance_of(L, R) {
  var O = R.prototype;
  L = L.__proto__;
  while (true) { 
    if (L === null) 
      return false; 
    if (O === L)// since L and R may be created by different vm, here use O == L may solve this problem.
      return true; 
    L = L.__proto__; 
  } 
 }

However, core problem is L and R may be created by different vm, so we do not know if other function have same problem with instanceof .

I am still finding better ways.

**Comment by mathiasrw** [comment]
sounds good. I cant imagine we are the first library to front this when running in a js vm

**Comment by mathiasrw** [comment]
@xlvector Have you found out anything new?

**Comment by xlvector** [comment]
Sorry, I does not find better solution.

I can only restrict my users can only do read operation in vm because write operation will generate new objects.

**Comment by mathiasrw** [comment]
:-(

**Comment by nickdeis** [comment]
If we replace everything with named functions for the prototypes, we could just change everything from 
```javascript
if(x instanceof yy.Y){
  //do something 
}else if (x instanceof yy.Z){
  //do something else
}
```
to
```javascript
switch(x.constructor.name){
  case "Y": 
    //do something;
    break;
  case "Z":
    //do something else;
    break;
}
```
This would probably be faster/result in less lines of code.

**NOTE:** Function.prototype.name is immutable if the function is named

**Comment by mathiasrw** [comment]
> If we replace everything with named functions for the prototypes, we could just change everything

Sounds interesting - but I dont quite get it. what is it exactly that needs to be replaced with a named function?

**Comment by nickdeis** [comment]
instead of attaching prototypes directly to yy, you "name" them first.
A named function is when you construct a function as follows:
```javascript
function Select(){

}
```
instead of
```javascript
yy.Select = function(){}
```
You then attach Select to yy later, like so
```javascript
yy.Select = Select;
```
The only reason I mention is that a direct consequence of using the syntax
```
export function Select(){}
```
For issue #445 is that all functions become named functions.

**Comment by mathiasrw** [comment]
@nickdeis I have paused changes in the ./src folder so we avoid a crazy merge with the ideas from #445 

Woul it be easyer for you if I change all `yy.Select = function(){}` to `function Select(){}`+`yy.Select = Select;`  in the ./src at the moment?

**Comment by nickdeis** [comment]
I don't use alasql nodejs (I have used it a lot in nashorn/rhino, the latter being the main reason I'm pursuing #445 ), I was just saw this ticket and found it interesting.

**Comment by mathiasrw** [comment]
:+1:

**Comment by nickdeis** [comment]
Yep. You can even keep the if/else if/else structure, I just find switch more expressive.
