### ISSUE TITLE
Passing in2.test

### ISSUE THREAD

**Issue by mathiasrw** [AlaSQL/alasql#502]
_Im closing #501 and opening this one with the new issues_

To be able to pass [in2.test](https://github.com/mathiasrw/alasql-logictest/blob/master/sqllogic/test/evidence/in2.test) the following statements must all raise an error (due to `t1` is not defined). 

``` sql
SELECT 1 FROM t1 WHERE 1 IN (SELECT 1,2)

SELECT 1 FROM t1 WHERE 1 IN (SELECT x,y FROM t1)

SELECT 1 FROM t1 WHERE 1 IN (SELECT * FROM t1)

SELECT 1 FROM t1 WHERE 1 IN (SELECT min(x),max(x) FROM t1)
```

**Comment by agershun** [comment]
@mathiasrw Could you look at the [test410.js](https://github.com/agershun/alasql/blob/develop/test/test410.js) - what is wrong in the current behavior?

**Comment by mathiasrw** [comment]
The test looks really fine. Ill see if I can replicate the issue from the test.
