### ISSUE TITLE
Setting for header ignored for xlsx

### ISSUE THREAD

**Issue by mathiasrw** [AlaSQL/alasql#700]
Setting `header:false` is ignored in the following example: http://jsfiddle.net/sd7822df/

It generates 2 worksheets both having headers...

**Comment by ashaik27** [comment]
Hi,

Is is possible to set headers:false and specify header names in a custom array.

**Comment by mathiasrw** [comment]
Having headers=true you can set header name by giving an alias to the select

`SELECT id, name , maxpaysomethig as Pay`

**Comment by ashaik27** [comment]
Good Morning,
 I have custom names specified using title for columns array as below.
 columns: [
              { columnid: 'localId', title: 'Local Id', width: 60, cell: },
              { columnid: 'lastName', title: 'Last Name', cell: },
        .....]
I am looking to achieve custom header names to group/sub group few headers by category. I fact I need 3 levels of header's get replaced with one level in the image.
![image](https://cloud.githubusercontent.com/assets/19956640/17521017/636a9ce2-5e17-11e6-9297-a83d4963a85b.png)
 
So I started looking for is there a way to specify or customize header's declaration out of column declaration/sql alias through a custom array .

Thanks

Thanks,
Aman

**Comment by mathiasrw** [comment]
You can not do that with alasql. For being creative with excel - please use https://github.com/SheetJS/js-xlsx

**Comment by ashaik27** [comment]
Great Thanks!
