### ISSUE TITLE
indexedDB.webkitGetDatabaseNames() is deprecated and will be removed from Chrome

### ISSUE THREAD

**Issue by inexorabletash** [AlaSQL/alasql#877]
Just a heads-up that per https://www.chromestatus.com/features/5725741740195840 we're planning on removing the non-standard `indexedDB.webkitGetDatabaseNames()` API from Chrome in M60, around August 2017.

It looks like AlaSQL.js will handle this properly since it already functions on other browsers, but I wanted to check in and ensure that this deprecation timeline will not have any unforeseen impact.

**Comment by mathiasrw** [comment]
You are awesome - thank you so much for letting us know.

Ill remove it from the source...

**Comment by morrme** [comment]
@mathiasrw there are 2 instances of this function used currently. What will you replace it with?

**Comment by mathiasrw** [comment]
I dont know. I have not had time to look into it. If you have any inputs please let me know...

**Comment by vibintv** [comment]
Need to store the created databases information as metadata and use that for returning database names.

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/2fUr-3wFPKI/discussion

**Comment by inexorabletash** [comment]
If this removal is going to be problematic (i.e. not enough time to adapt the library, etc), please respond to the blink-dev thread:

https://groups.google.com/a/chromium.org/d/topic/blink-dev/A6m1Pt9-BAo/discussion

**Comment by nguyenthuongquan** [comment]
window.indexedDB.webkitGetDatabaseNames().onsuccess = function(sender, args) { var r = sender.target.result; for (var i in r) indexedDB.deleteDatabase(r[i]);};

It is deprecated. Does anyone have any alternative way to clear index DB?

Thank you

**Comment by agershun** [comment]
На всякий случай - вот подробная информация

https://www.nalogia.ru/deductions/documents.php
https://www.nalogia.ru/deductions/mortgage.php



2017-08-09 13:34 GMT+03:00 Quan Nguyen <notifications@github.com>:

**Comment by mathiasrw** [comment]
?!?
