### ISSUE TITLE
'unable to resolve module 'fs' from 'location'' in react-native crna

### ISSUE THREAD

**Issue by jeresun** [AlaSQL/alasql#892]
I've installed alasql in my create-react-native-app project in npm. I include this line at the top of my class

`import alasql from 'alasq'`

I get this error when trying to run in expo

`"Unable to resolve module 'fs' from '[project_path]\node_modules\alasql\dist\dist\alasql.fs.js': Module does not exist in the module map or in these directories:..."`

But the files are clearly there in the node_modules folder, so I am confused. Thanks!

**Comment by mathiasrw** [comment]
You might want to try to do a

`'[project_path]\node_modules\alasql\dist\dist\alasql.js'`

?

**Comment by mathiasrw** [comment]
Did this solve it?

**Comment by jeresun** [comment]
sorry, that was a typo. there is only a single \dist directory. i still get the error

**Comment by mathiasrw** [comment]
You might want to try to do a

`'[project_path]\node_modules\alasql\dist\alasql.js'`

with no `.fs` in the end

**Comment by mathiasrw** [comment]
Woops - accidently closed...

**Comment by nickdeis** [comment]
Related to #913

**Comment by mathiasrw** [comment]
@jeresun Does https://github.com/agershun/alasql#use-webpack-and-browserify help you out?

**Comment by freemanon** [comment]
I'm also trying to use alasql in React Native. I see that in dist/alasql.js the `fs` related code is commented out, but there's still one `require('fs')` at [line 3114](https://github.com/agershun/alasql/blob/develop/dist/alasql.js#L3114)? Seems like the RN packager sees it and blows up.

Commenting out `exports.main` made it work for me.

**Comment by mathiasrw** [comment]
Wooooowwww - you are so right!

**Comment by mathiasrw** [comment]
The `require('fs')` does not present itself in the minified version...

Can you refer to `alasql.min.js` instead?
