### ISSUE TITLE
Alasql 2

### ISSUE THREAD

**Issue by agershun** [AlaSQL/alasql#94]
I opened this issue to collect requirements to the new major version of Alasql. Please write your ideas here. 
1. Change internal representation of data from array of objects to array of arrays. Now Alasql keed all internal data as array of objects, and it does not keep sequence of fields in the record.
2. Modular structure: I want to separate parser and database backends from SQL core. For example, I wrote [WebSQLShim parser](https://github.com/agershun/WebSQLShim), which can be used as one of parsers to the library. Other parsers can be separate subsets SQL like of T-SQL, MySQL, Oracle, and Postgress, and, of course, Alasql. Now Alasql has a mix of constructions from theses major dialects.
3. Replace objects to records as interface between parser and interpreter (and compiler). Now parser generates constructions like this:

``` js
    { $$ = new yy.DropDatabase({databaseid:$3}); }
```

but in WebSQLShim it is more logical and easy to interpret/compile (IMHO):

``` js
    { $$ = {statement: 'DROP DATABASE', databaseid:$3}; }
```

Please, write your ideas about this major change in the library. And sorry, I am very slow on this month with answers.

**Comment by mathiasrw** [comment]
So the idea is that you can build a costum alasql with the sql enterpreter you need? (and then combine it with the backend one like?)

**Comment by agershun** [comment]
Yes! It will be like a constructor. I feel, that Alasql can have two (or more) types of users:
a) Alasql as WebSQL replacer for Cordova, etc. (here WebSQL compatibility is important)
b) Alasql as JavaScript data manipulation library (and here all JavaScript extensiot like JSON processing are important)
c) Alalsql as light version of Oracle/SQLServer/MySQL for browser (and here compatibility issues are important fro each of databases SQL dialects)

**Comment by agershun** [comment]
Another two ideas for future: 
a) improve streaming functionality to allow process big data and use Alasql as filter
b) create or use  something fast and reliable as JavaScript database backend (may be LokiJS or PouchDB)

**Comment by mathiasrw** [comment]
WIth the b) here - are you thinking of stopping the development of the alasql and let it only be a layer on top of other backends?

**Comment by agershun** [comment]
No, I just want to mak a compatible version with some additional behaviour. 
Now, without orders in resulting set, Alasql can not make a proper UNION and other similar operators.

I think that Alasql has some interesting features:
a) Alasql's API with alasql function()
b) Alasql's SQL dialect with JavaScript integration, JSON objects, and INTO- and FROM- functions

From another point of view, some people need compatibility with SQLite, T-SQL, and other SQL dialects. Plus the libraryr size is the matter. Now the parser is about 150K - it is a half of whole library size, and it can be reduced either with another parser, or by splitting main parser to subsets.

So, it can be a combinatons of:
a) full features package
b) separate subsets for different SQL dialects 
c) data manipulation library (primarily for SELECT and JOINS)
d) number of INTO- and FROM- functions 
e) database backends

Also, I am still thinking about reliability and transactions (now it is a weak part of the library).

**Comment by wuxianliang** [comment]
Would  you like to support OrientDB which is a document-graph database using SQL as query language? Just like Meteor-Postegres Project, if alasql.js supports OrientDB, we can build a robust Meteor-OrientDB package more easily.  Then we can SQL tables, json, and graphs in Meteor which is great!

**Comment by agershun** [comment]
I will read about OrientDB and write the answer. I like the idea to extand AlaSQL';s JSON functionality to non-relational databases. Thank you!

**Comment by wuxianliang** [comment]
Thank you very much! http://orientdb.com/  http://orientdb.com/docs/last/

**Comment by mathiasrw** [comment]
8 years old. Im closing...
